const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const source=fs.readFileSync('public/get-droned/assets/js/game.js','utf8'),ast=ts.createSourceFile('game.js',source,99,true),functions={};
(function visit(n){if(ts.isFunctionDeclaration(n)&&n.name)functions[n.name.text]=n.getText(ast);ts.forEachChild(n,visit)})(ast);
function setup(){const c={Math,performance:{now:()=>100},touchControls:{matches:true},mouseAim:{active:false},player:{x:0,y:0,face:0,nades:2},enemies:[],piloting:false,aboard:false,mobileLock:null,mobileLockUntil:0,los:()=>true,smokeBlocked:()=>false,state:'play',nades:[],manualAim:()=>false,nearestTarget:()=>{throw Error('mobile grenade must not select target')},sfx(){},hud(){},touchFire:{id:null},actDown(){},actUp(){},};vm.createContext(c);vm.runInContext(['mobileAimTarget','throwNade','touchFireStart','touchFireMove','touchFireEnd'].map(n=>functions[n]).join('\n'),c);return c;}
function enemy(deg){return {x:200*Math.cos(deg*Math.PI/180),y:200*Math.sin(deg*Math.PI/180),hp:100};}
test('mobile cone accepts 14 degrees, rejects 16 degrees and obstructed enemies',()=>{const c=setup(),a=enemy(14),b=enemy(16);c.enemies=[b,a];assert.equal(c.mobileAimTarget(300),a);c.los=()=>false;assert.equal(c.mobileAimTarget(300),null);});
test('target stays stable briefly but immediately releases dead targets',()=>{const c=setup(),a=enemy(10),b=enemy(1);c.enemies=[a];assert.equal(c.mobileAimTarget(300),a);c.enemies.push(b);assert.equal(c.mobileAimTarget(300),a);a.hp=0;assert.equal(c.mobileAimTarget(300),b);c.player.face=Math.PI;assert.equal(c.mobileAimTarget(300),null);});
test('mobile frag lands forward instead of snapping to an enemy',()=>{const c=setup();c.enemies=[enemy(14)];c.throwNade();assert.equal(c.nades.length,1);assert.equal(c.nades[0].tx,220);assert.equal(c.nades[0].ty,0);assert.equal(c.player.nades,1);});
test('fire drag tracks only its own finger and releasing movement finger does not stop fire',()=>{const c=setup(),event=(id,x,y)=>({changedTouches:[{identifier:id,clientX:x,clientY:y}],preventDefault(){}});c.touchFireStart(event(7,50,50));c.touchFireMove(event(2,50,100));assert.equal(c.touchFire.aiming,false);c.touchFireMove(event(7,50,100));assert.equal(c.player.face,Math.PI/2);c.touchFireEnd(event(2,50,100));assert.equal(c.touchFire.id,7);c.touchFireEnd(event(7,50,100));assert.equal(c.touchFire.id,null);assert.equal(c.player.face,Math.PI/2);});
